//! Conformance test for [`tritium_nn::rope_apply`] against the committed torch
//! goldens (`tests/goldens/rope.json`), generated by `tools/gen_op_goldens.py`
//! from the *exact* `transformers.models.bitnet` `rotate_half` /
//! `apply_rotary_pos_emb` functions.
//!
//! Convention pinned here: NeoX-style "half-rotated" RoPE. The `head_dim`-vector
//! is split in half; lane `j` in `[0, head_dim/2)` pairs with lane `j + head_dim/2`
//! with `theta_j = pos * theta^(-2j/head_dim)`, rotated as
//! `(x1*cos - x2*sin, x2*cos + x1*sin)`. Buffer layout is
//! `[n_token, n_head, head_dim]` row-major; `positions[t]` is the absolute
//! position of token `t`.
//!
//! Tolerance: ADR-0004 non-ternary fp32 <= 2e-3 relative.

use serde::Deserialize;
use tritium_nn::rope_apply;

/// ADR-0004 relative tolerance for non-ternary fp32 ops.
const REL_TOL: f32 = 2e-3;

#[derive(Debug, Deserialize)]
struct Golden {
    op: String,
    cases: Vec<Case>,
}

#[derive(Debug, Deserialize)]
struct Case {
    id: String,
    params: Params,
    inputs: Inputs,
    expected_output: Expected,
}

#[derive(Debug, Deserialize)]
struct Params {
    n_token: usize,
    n_head: usize,
    head_dim: usize,
    theta: f32,
    positions: Vec<usize>,
}

#[derive(Debug, Deserialize)]
struct Inputs {
    x: Vec<f32>,
}

#[derive(Debug, Deserialize)]
struct Expected {
    out: Vec<f32>,
}

fn load_goldens() -> Golden {
    let path = concat!(env!("CARGO_MANIFEST_DIR"), "/tests/goldens/rope.json");
    let bytes = std::fs::read(path).expect("read rope golden");
    serde_json::from_slice(&bytes).expect("parse rope golden")
}

/// Assert `got` matches `want` element-wise within `REL_TOL` relative error
/// (with an absolute-error fallback so values near zero are graded sensibly).
fn assert_close(case_id: &str, got: &[f32], want: &[f32]) {
    assert_eq!(
        got.len(),
        want.len(),
        "case {case_id}: length mismatch got {} want {}",
        got.len(),
        want.len(),
    );
    for (i, (&g, &w)) in got.iter().zip(want.iter()).enumerate() {
        let denom = w.abs().max(1.0);
        let rel = (g - w).abs() / denom;
        assert!(
            rel <= REL_TOL,
            "case {case_id}: idx {i} rel err {rel} exceeds {REL_TOL} (got {g}, want {w})",
        );
    }
}

#[test]
fn rope_matches_torch_goldens() {
    let golden = load_goldens();
    assert_eq!(golden.op, "rope", "unexpected op in golden file");
    assert!(!golden.cases.is_empty(), "no rope cases in golden file");

    for case in &golden.cases {
        // Sanity: golden shape matches the declared layout.
        let expected_len = case.params.n_token * case.params.n_head * case.params.head_dim;
        assert_eq!(
            case.inputs.x.len(),
            expected_len,
            "case {}: input x length disagrees with n_token*n_head*head_dim",
            case.id,
        );
        assert_eq!(
            case.params.positions.len(),
            case.params.n_token,
            "case {}: positions length disagrees with n_token",
            case.id,
        );

        let mut x = case.inputs.x.clone();
        rope_apply(
            &mut x,
            &case.params.positions,
            case.params.n_head,
            case.params.head_dim,
            case.params.theta,
        )
        .unwrap_or_else(|e| panic!("case {}: rope_apply failed: {e}", case.id));

        assert_close(&case.id, &x, &case.expected_output.out);
    }
}

/// Position 0 is an identity rotation (all angles are zero) — the op must leave
/// the buffer untouched, which the `pos-0` golden also encodes.
#[test]
fn rope_position_zero_is_identity() {
    let mut x = vec![0.5_f32, -1.25, 3.0, 0.0, -2.5, 7.0, -0.125, 4.0];
    let orig = x.clone();
    rope_apply(&mut x, &[0], 1, 8, 500_000.0).expect("rope_apply pos 0");
    assert_eq!(x, orig, "RoPE at position 0 must be the identity");
}

/// A shape disagreement must surface as `NnError::Shape`, never a panic.
#[test]
fn rope_shape_mismatch_is_error() {
    let mut x = vec![0.0_f32; 7]; // not n_token*n_head*head_dim = 1*1*8
    let err = rope_apply(&mut x, &[0], 1, 8, 500_000.0);
    assert!(matches!(err, Err(tritium_nn::NnError::Shape { .. })));
}

/// An odd `head_dim` cannot be split into rotation pairs and must error out
/// rather than panic.
#[test]
fn rope_odd_head_dim_is_error() {
    let mut x = vec![0.0_f32; 3];
    let err = rope_apply(&mut x, &[0], 1, 3, 500_000.0);
    assert!(matches!(err, Err(tritium_nn::NnError::Shape { .. })));
}
