//! HELD-OUT SALT distillation (plan 0042) — the generalization test, and the prerequisite for any
//! publishable number. Unlike `salt_distill_real` (which trains + evaluates on ONE sequence =
//! in-sample memorization), this distills SmolLM2 on a TRAIN token split and measures perplexity on
//! a disjoint HELD-OUT split it never trains on. Recovering held-out ppl vs PTQ = real generalization.
//!
//! Corpus: `tools/reference/heldout_corpus.json` ({train_ids, eval_ids}), generated by
//! `tools/gen_corpus.py` (a public-domain text tokenized with the model's own tokenizer).
//! `#[ignore]`d (slow, needs SmolLM2-135M); run:
//!
//! ```text
//! cargo test -p tritium-nn --release --test salt_distill_heldout -- --ignored --nocapture
//! ```

mod common;

use std::path::PathBuf;

use common::{extract, forward, logits_of, perplexity_windowed};
// `Calib`, `calibrate` and `fold` are used only by the cuda-gated
// `salt_distillation_device_trainer_recovers_heldout` test below.
#[cfg(feature = "cuda")]
use common::{Calib, calibrate, fold};
use tritium_nn::ModelRunner;
use tritium_train::ops::ste;
use tritium_train::{AdamW, Optimizer, Tape};
// The LR schedule is consumed only by the cuda-gated resident-trainer path.
#[cfg(feature = "cuda")]
use tritium_train::LrSchedule;

const T: usize = 2;
const TRAIN_SEQ: usize = 32; // window length for the training corpus
const STEPS: u64 = 40; // committed-gate default; TRITIUM_DISTILL_STEPS overrides for a real run
const LR: f32 = 2e-3;
/// Held-out perplexity is scored in non-overlapping windows of this many tokens. CPU eval memory is
/// QUADRATIC in the evaluated length — the tape retains one `[seq, seq]` attention matrix per head
/// per layer — so a single-shot eval of a large held-out set OOMs the machine: 4096 tokens costs
/// `30 layers · 9 heads · 4096² · 4 B ≈ 18 GB`. A 512-token window bounds the peak at ~283 MB.
/// Chosen ≥ the committed fixture's 256-token eval so that corpus still scores in ONE window — the
/// committed gate numbers are therefore unchanged by the switch to windowed scoring.
const EVAL_WINDOW: usize = 512;

fn model_dir() -> PathBuf {
    let home = std::env::var("HOME").unwrap_or_default();
    PathBuf::from(home).join(".cache/tritium-models/smollm2-135m")
}

fn corpus() -> (Vec<u32>, Vec<u32>) {
    // TRITIUM_CORPUS overrides the committed fixture (for the large-budget endpoint sweeps, which
    // use a bigger locally-generated corpus we don't commit as a multi-MB fixture).
    let path = std::env::var("TRITIUM_CORPUS").unwrap_or_else(|_| {
        concat!(
            env!("CARGO_MANIFEST_DIR"),
            "/../../tools/reference/heldout_corpus.json"
        )
        .to_string()
    });
    let j: serde_json::Value =
        serde_json::from_slice(&std::fs::read(&path).expect("corpus json")).expect("parse");
    let ids = |k: &str| {
        j[k].as_array()
            .expect(k)
            .iter()
            .map(|v| v.as_u64().expect("id") as u32)
            .collect::<Vec<u32>>()
    };
    (ids("train_ids"), ids("eval_ids"))
}

fn row_softmax(logits: &[f32], vocab: usize) -> Vec<f32> {
    let mut p = logits.to_vec();
    for row in p.chunks_mut(vocab) {
        let m = row.iter().copied().fold(f32::NEG_INFINITY, f32::max);
        let mut s = 0.0f32;
        for v in row.iter_mut() {
            *v = (*v - m).exp();
            s += *v;
        }
        for v in row.iter_mut() {
            *v /= s;
        }
    }
    p
}

#[test]
#[ignore = "slow held-out real-model distillation; needs SmolLM2-135M; run explicitly"]
fn salt_distillation_recovers_heldout_perplexity() {
    let dir = model_dir();
    if !dir.join("model.safetensors").exists() {
        eprintln!("skipping: {} absent", dir.display());
        return;
    }
    let steps: u64 = std::env::var("TRITIUM_DISTILL_STEPS")
        .ok()
        .and_then(|s| s.parse().ok())
        .unwrap_or(STEPS);

    let runner =
        ModelRunner::from_hf(&dir, Box::new(tritium_cpu::CpuBackend::new())).expect("from_hf");
    let (a, fp, shapes) = extract(&runner);
    let (mut train_ids, eval_ids) = corpus();
    // Cap the train pool to sweep the recovery-vs-tokens curve (held-out set is fixed & disjoint).
    if let Some(n) = std::env::var("TRITIUM_TRAIN_TOKENS")
        .ok()
        .and_then(|s| s.parse().ok())
    {
        train_ids.truncate(n);
    }

    // Non-overlapping training windows.
    let windows: Vec<&[u32]> = train_ids.chunks_exact(TRAIN_SEQ).collect();
    assert!(!windows.is_empty(), "train corpus shorter than one window");

    // Held-out baselines (fp + full PTQ), on the disjoint eval split.
    let ppl_fp = perplexity_windowed(&fp, &a, &eval_ids, EVAL_WINDOW);
    let ptq: Vec<Vec<f32>> = fp
        .iter()
        .zip(&shapes)
        .map(|(wf, &(n, k))| ste::salt_quantize_forward(wf, n, k, T))
        .collect();
    let ppl_ptq = perplexity_windowed(&ptq, &a, &eval_ids, EVAL_WINDOW);

    // Distill on the TRAIN windows (cycled), AdamW; eval held-out afterwards.
    let mut lat = fp.clone();
    let opt = AdamW::new(LR);
    let mut states: Vec<_> = lat.iter().map(|w| opt.init_state(w.len())).collect();
    let (mut first, mut last) = (f32::NAN, f32::NAN);

    // Optional GPU student (plan 0043 Phase 1): route the tape's `dense_matmul`s to the 4090 via the
    // bit-exact `train_grad.cu` kernels. Opt-in with `TRITIUM_DISTILL_GPU=1 --features cuda`; the
    // teacher forward + `salt_ste` + norm/softmax glue stay on the CPU host (device-resident = P2).
    #[cfg(feature = "cuda")]
    let gpu: Option<std::rc::Rc<dyn tritium_train::TrainGemm>> =
        std::env::var("TRITIUM_DISTILL_GPU").is_ok().then(|| {
            std::rc::Rc::new(tritium_cuda::train::GpuGemm::new(0).expect("open CUDA device"))
                as std::rc::Rc<dyn tritium_train::TrainGemm>
        });
    #[cfg(feature = "cuda")]
    let backend = if gpu.is_some() { "GPU" } else { "CPU" };
    #[cfg(not(feature = "cuda"))]
    let backend = "CPU";
    let mut step_ms = 0.0f64;

    for step in 1..=steps {
        let t_start = std::time::Instant::now();
        let wi = ((step - 1) as usize) % windows.len();
        let toks = windows[wi];
        // Teacher soft targets for this window, computed on the fly (O(1) memory — precomputing all
        // windows' full-vocab probs is ~26GB at the 128k-token endpoint).
        let tprobs = row_softmax(&logits_of(&fp, &a, toks), a.vocab);
        #[cfg(feature = "cuda")]
        let mut t = match &gpu {
            Some(e) => Tape::with_gemm(e.clone()),
            None => Tape::new(),
        };
        #[cfg(not(feature = "cuda"))]
        let mut t = Tape::new();
        let mut leaf_ids = Vec::with_capacity(lat.len());
        let mut ste_ids = Vec::with_capacity(lat.len());
        for (i, wv) in lat.iter().enumerate() {
            let l = t.leaf(wv.clone());
            let (n, k) = shapes[i];
            ste_ids.push(t.salt_ste(l, n, k, T));
            leaf_ids.push(l);
        }
        let logits = forward(&mut t, &ste_ids, &a, toks);
        let tg = t.leaf(tprobs);
        let l = t.softmax_xent(logits, tg, TRAIN_SEQ, a.vocab);
        let lv = t.value(l)[0];
        if step == 1 {
            first = lv;
        }
        last = lv;
        let grads = t.backward(l);
        for i in 0..lat.len() {
            opt.step(step, &mut lat[i], &grads[leaf_ids[i]], &mut states[i]);
        }
        step_ms += t_start.elapsed().as_secs_f64() * 1e3;
        if step % 10 == 0 || step == 1 {
            eprintln!("  step {step}/{steps} (win {wi})  train-xent {lv:.4}");
        }
    }
    eprintln!(
        "  [{backend}] mean step {:.0}ms over {steps} steps (teacher+salt_ste CPU; matmuls {backend})",
        step_ms / steps as f64
    );
    let distilled: Vec<Vec<f32>> = lat
        .iter()
        .zip(&shapes)
        .map(|(wf, &(n, k))| ste::salt_quantize_forward(wf, n, k, T))
        .collect();
    let ppl_distilled = perplexity_windowed(&distilled, &a, &eval_ids, EVAL_WINDOW);

    println!(
        "0042 HELD-OUT SmolLM2 distillation (T={T}, {steps} steps, train {} tok / {} windows, eval {} HELD-OUT tok): \
         fp ppl {ppl_fp:.3} | PTQ ppl {ppl_ptq:.3e} | distilled ppl {ppl_distilled:.3}  \
         (train-xent {first:.3}→{last:.3}). GENERALIZES: held-out ppl {:.0}× better than PTQ on unseen text \
         (not memorization). DATA-LIMITED: still {:.1}× fp at this budget — the residual gap is what more \
         tokens close (a point on the recovery-vs-tokens curve; sweep TRITIUM_TRAIN_TOKENS to trace it, 0042).",
        train_ids.len(),
        windows.len(),
        eval_ids.len(),
        ppl_ptq / ppl_distilled,
        ppl_distilled / ppl_fp,
    );

    assert!(ppl_ptq > ppl_fp, "PTQ must degrade held-out ppl");
    assert!(last < first, "training surrogate must decrease");
    // The load-bearing claim: end-to-end distillation on TRAIN recovers HELD-OUT ppl vs PTQ — real
    // generalization, not the in-sample memorization of salt_distill_real. (Full recovery to fp
    // needs more tokens — the recovery-vs-tokens curve; this budget is one point on it.)
    assert!(
        ppl_distilled < 0.5 * ppl_ptq,
        "distillation must recover held-out ppl vs PTQ: {ppl_distilled:.3} vs PTQ {ppl_ptq:.3e}"
    );
}

/// Device-resident SALT distillation (plan 0043 P2.5d): the SAME held-out distillation as above, but
/// the student model forward+backward AND the teacher forward run on the GPU `DeviceTape` instead of
/// the CPU autograd tape. `salt_ste` stays on the host — quantize the masters each step; its STE
/// backward is identity ([`ste::salt_quantize_vjp`] = `grad_out`), so the device gradient w.r.t. the
/// quantized weight IS the master gradient (no device salt_ste kernel needed). Proves the device
/// engine recovers held-out ppl like the CPU path, and measures the per-step speedup.
#[cfg(feature = "cuda")]
#[test]
#[ignore = "slow device distillation; needs SmolLM2-135M + a CUDA device; run explicitly"]
fn salt_distillation_device_tape_recovers_heldout() {
    use std::time::Instant;

    use common::device_forward;
    use tritium_cuda::CudaBackend;
    use tritium_cuda::train::DeviceTape;

    let dir = model_dir();
    if !dir.join("model.safetensors").exists() {
        eprintln!("skipping: {} absent", dir.display());
        return;
    }
    let steps: u64 = std::env::var("TRITIUM_DISTILL_STEPS")
        .ok()
        .and_then(|s| s.parse().ok())
        .unwrap_or(STEPS);
    let runner =
        ModelRunner::from_hf(&dir, Box::new(tritium_cpu::CpuBackend::new())).expect("from_hf");
    let (a, fp, shapes) = extract(&runner);
    let (mut train_ids, eval_ids) = corpus();
    if let Some(n) = std::env::var("TRITIUM_TRAIN_TOKENS")
        .ok()
        .and_then(|s| s.parse().ok())
    {
        train_ids.truncate(n);
    }

    let windows: Vec<&[u32]> = train_ids.chunks_exact(TRAIN_SEQ).collect();
    assert!(!windows.is_empty(), "train corpus shorter than one window");

    let backend = CudaBackend::new(0).expect("open CUDA device");

    // Held-out baselines (fp + full PTQ) on the disjoint eval split.
    let ppl_fp = perplexity_windowed(&fp, &a, &eval_ids, EVAL_WINDOW);
    let ptq: Vec<Vec<f32>> = fp
        .iter()
        .zip(&shapes)
        .map(|(wf, &(n, k))| ste::salt_quantize_forward(wf, n, k, T))
        .collect();
    let ppl_ptq = perplexity_windowed(&ptq, &a, &eval_ids, EVAL_WINDOW);

    let mut lat = fp.clone();
    let opt = AdamW::new(LR);
    let mut states: Vec<_> = lat.iter().map(|w| opt.init_state(w.len())).collect();
    let mut step_ms = 0.0f64;
    for step in 1..=steps {
        let t0 = Instant::now();
        let wi = ((step - 1) as usize) % windows.len();
        let toks = windows[wi];
        let tokens_i32: Vec<i32> = toks.iter().map(|&t| t as i32).collect();
        // Teacher: device forward with the fp weights → soft targets (tape dropped after readout).
        let tprobs = {
            let mut tt = DeviceTape::new(&backend, a.vocab).unwrap();
            let (tlogits, _) = device_forward(&mut tt, &a, &fp, &tokens_i32, TRAIN_SEQ);
            row_softmax(&tt.value(tlogits).unwrap(), a.vocab)
        };
        // Student: quantize masters (host salt_ste forward), device fwd+bwd → master grads (identity STE).
        let quantized: Vec<Vec<f32>> = lat
            .iter()
            .zip(&shapes)
            .map(|(w, &(n, k))| ste::salt_quantize_forward(w, n, k, T))
            .collect();
        let mut st = DeviceTape::new(&backend, a.vocab).unwrap();
        let (slogits, wids) = device_forward(&mut st, &a, &quantized, &tokens_i32, TRAIN_SEQ);
        let grads = st
            .xent_backward(slogits, &tprobs, TRAIN_SEQ, a.vocab, &wids)
            .unwrap();
        for i in 0..lat.len() {
            opt.step(step, &mut lat[i], &grads[i], &mut states[i]);
        }
        step_ms += t0.elapsed().as_secs_f64() * 1e3;
        if step % 10 == 0 || step == 1 {
            eprintln!("  step {step}/{steps} (win {wi})");
        }
    }

    let distilled: Vec<Vec<f32>> = lat
        .iter()
        .zip(&shapes)
        .map(|(wf, &(n, k))| ste::salt_quantize_forward(wf, n, k, T))
        .collect();
    let ppl_distilled = perplexity_windowed(&distilled, &a, &eval_ids, EVAL_WINDOW);
    println!(
        "0043 P2.5d DEVICE SALT distillation (T={T}, {steps} steps, {} tok / {} win, eval {} HELD-OUT): \
         fp ppl {ppl_fp:.3} | PTQ ppl {ppl_ptq:.3e} | distilled ppl {ppl_distilled:.3}. \
         Recovers {:.0}× vs PTQ. Mean device step {:.0}ms (teacher fwd + student fwd+bwd on GPU; \
         salt_ste quantize on host).",
        train_ids.len(),
        windows.len(),
        eval_ids.len(),
        ppl_ptq / ppl_distilled,
        step_ms / steps as f64,
    );
    assert!(ppl_ptq > ppl_fp, "PTQ must degrade held-out ppl");
    assert!(
        ppl_distilled < 0.5 * ppl_ptq,
        "device distillation must recover held-out ppl vs PTQ: {ppl_distilled:.3} vs {ppl_ptq:.3e}"
    );
}

/// ADR 0027 Track A exit gate: the student master's SALT reconstruction,
/// forward/backward gradients, and AdamW state remain in VRAM for every step.
/// Only teacher probabilities and token ids cross the host boundary.
#[cfg(feature = "cuda")]
#[test]
#[ignore = "slow resident-trainer distillation; needs SmolLM2-135M + CUDA; run explicitly"]
fn salt_distillation_device_trainer_recovers_heldout() {
    use std::time::Instant;

    use common::{device_forward, device_forward_resident};
    use tritium_cuda::CudaBackend;
    use tritium_cuda::train::{
        DeviceTape, DeviceTensor, DeviceTrainParam, DeviceTrainer, DeviceTrainerWeightStorage,
        MasterPrecision, MomentPrecision, SaltGrouping, TensorCoreGemm,
    };
    use tritium_format::TeacherCacheHeader;
    use tritium_nn::{
        ModelWeights, TeacherCacheReader, TiedSwiGluTrainingModel, hash_teacher_corpus,
        semantic_training_model_digest,
    };

    const TRACK0_STEP_MS: f64 = 1123.0;

    let dir = model_dir();
    if !dir.join("model.safetensors").exists() {
        eprintln!("skipping: {} absent", dir.display());
        return;
    }
    let steps: u64 = std::env::var("TRITIUM_DISTILL_STEPS")
        .ok()
        .and_then(|s| s.parse().ok())
        .unwrap_or(STEPS);
    // Sweepable SALT plane count and training-window length, shadowing the file consts so the whole
    // test body (including the summary format strings) picks them up with no other edits. Defaults
    // are the committed const values, so the gate is unchanged when neither var is set.
    let planes: usize = std::env::var("TRITIUM_DISTILL_PLANES")
        .ok()
        .and_then(|s| s.parse().ok())
        .filter(|t| (1..=3).contains(t)) // the SALT residual stack supports 1..=3 planes
        .unwrap_or(T);
    let seq_len: usize = std::env::var("TRITIUM_DISTILL_SEQ")
        .ok()
        .and_then(|s| s.parse().ok())
        .filter(|&s| s >= 2)
        .unwrap_or(TRAIN_SEQ);
    let (config, spec, weights) = ModelWeights::load_hf(&dir).expect("load_hf");
    let training_model =
        TiedSwiGluTrainingModel::extract(&config, &spec, &weights).expect("training model");
    let teacher_model_digest = semantic_training_model_digest(&config, &spec, &training_model);
    let runner =
        ModelRunner::from_weights(config, weights, Box::new(tritium_cpu::CpuBackend::new()));
    let (a, fp, shapes) = extract(&runner);
    let (mut train_ids, eval_ids) = corpus();
    if let Some(n) = std::env::var("TRITIUM_TRAIN_TOKENS")
        .ok()
        .and_then(|s| s.parse().ok())
    {
        train_ids.truncate(n);
    }

    // Activation-aware salience fold (TRITIUM_DISTILL_SMOOTH=<alpha>). The single largest PTQ win
    // measured (78x at T=1; 1.74x -> 1.40x at T=3), and free at inference: every inverse lands in an
    // fp norm gain or in a row scale the fitter already carries. Applied BEFORE the masters are
    // uploaded, so the student trains in the folded basis and `a`'s norms carry the inverse --
    // which also means every downstream eval must use the returned `a`, not the original.
    //
    // alpha MUST be calibrated per model: the optimum shifts down with size (0.75 at 135M, 0.50 at
    // 360M) and the wrong one costs 4.2x at T=1. Deliberately no default.
    let (a, fp) = match std::env::var("TRITIUM_DISTILL_SMOOTH")
        .ok()
        .and_then(|v| v.parse::<f64>().ok())
    {
        None => (a, fp),
        Some(alpha) => {
            const CALIB_WINDOWS: usize = 8;
            const CALIB_SEQ: usize = 512;
            assert!(
                train_ids.len() >= CALIB_WINDOWS * CALIB_SEQ,
                "salience calibration needs {} train tokens, got {}",
                CALIB_WINDOWS * CALIB_SEQ,
                train_ids.len()
            );
            let mut calib = Calib::new(&a);
            for w in 0..CALIB_WINDOWS {
                calibrate(
                    &fp,
                    &a,
                    &train_ids[w * CALIB_SEQ..(w + 1) * CALIB_SEQ],
                    &mut calib,
                );
            }
            let (folded, farch) = fold(&fp, &shapes, &a, &calib, alpha);
            println!(
                "salience fold applied: alpha={alpha} over {} calibration tokens (train split)",
                calib.rows
            );
            (farch, folded)
        }
    };

    let windows: Vec<&[u32]> = train_ids.chunks_exact(seq_len).collect();
    assert!(!windows.is_empty(), "train corpus shorter than one window");

    let backend = CudaBackend::new(0).expect("open CUDA device");
    // Opt-in tensor-core tier (Lever 1): route the resident trainer's dense forward + backward
    // GEMMs through tf32 tensor cores. Off by default so the committed recovery gate stays on the
    // bit-exact f32 path; set TRITIUM_DISTILL_TF32=1 to validate that recovery still holds on tf32.
    let tc = std::env::var("TRITIUM_DISTILL_TF32")
        .is_ok()
        .then(|| TensorCoreGemm::new(&backend).expect("cuBLASLt tensor-core tier"));
    let ppl_fp = perplexity_windowed(&fp, &a, &eval_ids, EVAL_WINDOW);

    // The SALT fitter the student is actually trained through (see `grouping` below). Deciding it
    // here so the PTQ baseline, every curve point, and the final score all quantize the SAME way
    // the trainer does.
    //
    // This used to be `ste::salt_quantize_forward` unconditionally -- the legacy per-row AbsMean
    // fitter -- while training ran the grouped+ITF+rotation one. Every checkpoint was then scored by
    // a quantizer the student had never optimised against, which measures how far the master drifted
    // out of the per-row basin rather than how well it trained. Rotation was penalised hardest,
    // because rotation is precisely what lets a master specialise into a basis a single per-row
    // scale cannot represent.
    let group_cfg: Option<usize> = std::env::var("TRITIUM_DISTILL_GROUP")
        .ok()
        .and_then(|v| v.parse().ok());
    let itf_cfg: usize = std::env::var("TRITIUM_DISTILL_ITF")
        .ok()
        .and_then(|v| v.parse().ok())
        .unwrap_or(5);
    let rot_cfg = match std::env::var("TRITIUM_DISTILL_ROTATE").as_deref() {
        Ok("auto") => ste::RotationPolicy::Auto,
        Ok("always") => ste::RotationPolicy::Always,
        _ => ste::RotationPolicy::Never,
    };
    // Frozen at the INITIAL weights, exactly as `DeviceTrainer::new_with_fitter` freezes it, so the
    // evaluator can never re-decide on a master training has moved.
    let rot_masks: Option<Vec<Vec<u8>>> = group_cfg.map(|g| {
        fp.iter()
            .zip(&shapes)
            .map(|(wf, &(n, k))| ste::rotation_mask(wf, n, k, planes, g, itf_cfg, rot_cfg))
            .collect()
    });
    let deploy_quantize = |w: &[f32], n: usize, k: usize, i: usize| -> Vec<f32> {
        match (group_cfg, &rot_masks) {
            (Some(g), Some(masks)) => {
                ste::salt_quantize_forward_grouped_masked(w, n, k, planes, g, itf_cfg, &masks[i])
            }
            _ => ste::salt_quantize_forward(w, n, k, planes),
        }
    };

    let ptq: Vec<Vec<f32>> = fp
        .iter()
        .zip(&shapes)
        .enumerate()
        .map(|(i, (wf, &(n, k)))| deploy_quantize(wf, n, k, i))
        .collect();
    let ppl_ptq = perplexity_windowed(&ptq, &a, &eval_ids, EVAL_WINDOW);

    let opt = AdamW::new(LR);
    let specs: Vec<_> = fp
        .iter()
        .zip(&shapes)
        .map(|(master, &(rows, cols))| DeviceTrainParam {
            master,
            rows,
            cols,
            salt_planes: planes,
            optimizer: opt,
        })
        .collect();
    // Lever 5: TRITIUM_DISTILL_INT8=1 holds the AdamW moments block-wise int8 (the A/B against the
    // committed f32 gate — does the quantized optimizer still recover ~960× on the real model?).
    let moment_precision = if std::env::var("TRITIUM_DISTILL_INT8").is_ok() {
        MomentPrecision::Int8
    } else {
        MomentPrecision::F32
    };
    // TRITIUM_DISTILL_BF16MASTER=1 confines the master to the bf16 grid with stochastic rounding —
    // does a bf16 master still recover ~960× on the real model? (numerically a real bf16 master).
    let master_precision = if std::env::var("TRITIUM_DISTILL_BF16MASTER").is_ok() {
        MasterPrecision::Bf16
    } else {
        MasterPrecision::F32
    };
    // The grouped+rotated+ITF fitter (TRITIUM_DISTILL_GROUP=<g>). Absent keeps the legacy per-row
    // AbsMean reconstruction, which every prior distillation run used and which PTQ measured at
    // 10786x fp -- so a real run should always set it. 128 is the PTQ convention; 256 is TQ2_0's
    // deployed block.
    let grouping = group_cfg.map(|group| SaltGrouping {
        group,
        // Rotation defaults to Never FOR TRAINING, which is the opposite of the PTQ default,
        // and the difference is measured rather than assumed. Held-out ppl at steps 5/10/15/20,
        // 135M, T=2, g128 (legacy per-row control ends at 4247 / 500x):
        //
        //   greedy, no rotation   3.9M -> 70k -> 33.8k -> 18.1k   monotone, 117x
        //   greedy, rotation Auto 456k -> 65k -> 79k UP -> 40.6k  OSCILLATES, 52x
        //   ITF=5, no rotation    117k -> 6547 -> 6472 -> 3692    monotone, 575x  <- best
        //   ITF=5, rotation Auto  5.5M -> 71k -> 1.9M UP -> 1.8M  OSCILLATES, 1x
        //
        // So ITF helps training (575x beats the 500x control) while rotation destabilises it,
        // with or without ITF. The likely cause is the STE: `salt_quantize_vjp` is the identity,
        // but under a Hadamard every coordinate of a group feeds that group's scale in BOTH
        // directions, so the forward is far more sensitive to a master perturbation than the
        // identity assumes -- an effectively too-large step. Rotation is the single biggest PTQ
        // win (548x at T=3), so it stays the PTQ default; making it usable in training needs a
        // rotation-aware backward or a lower LR, not just this switch.
        //
        // TRITIUM_DISTILL_ROTATE=auto|always re-enables it for that investigation.
        rotation: match std::env::var("TRITIUM_DISTILL_ROTATE").as_deref() {
            Ok("auto") => ste::RotationPolicy::Auto,
            Ok("always") => ste::RotationPolicy::Always,
            _ => ste::RotationPolicy::Never,
        },
        iters: std::env::var("TRITIUM_DISTILL_ITF")
            .ok()
            .and_then(|v| v.parse().ok())
            .unwrap_or(5),
    });
    if let Some(g) = grouping {
        println!(
            "SALT fitter: g{} +ITF({}) +rotation({:?})",
            g.group, g.iters, g.rotation
        );
    }
    let mut trainer = DeviceTrainer::new_with_fitter(
        &backend,
        &specs,
        DeviceTrainerWeightStorage::DenseQuantized,
        moment_precision,
        master_precision,
        grouping,
    )
    .expect("upload resident state");
    let mut teacher_cache = std::env::var_os("TRITIUM_TEACHER_CACHE").map(|path| {
        let expected = TeacherCacheHeader {
            seq_len: seq_len as u32,
            vocab: a.vocab as u32,
            windows: windows.len() as u64,
            model_hash: teacher_model_digest,
            corpus_hash: hash_teacher_corpus(&train_ids, seq_len as u32),
        };
        TeacherCacheReader::open(path, &expected).expect("open matching teacher cache")
    });
    let mut cached_target = vec![0.0; seq_len * a.vocab];

    // Step-1 recovery-vs-tokens curve (plan 0042): set TRITIUM_DISTILL_CURVE=K to evaluate held-out
    // ppl every K steps and print one curve point per checkpoint, tracing the whole convergence in a
    // single run instead of re-training from scratch per budget. Off by default so the committed gate
    // (40 steps, one final eval) is unchanged.
    let curve_every: Option<u64> = std::env::var("TRITIUM_DISTILL_CURVE")
        .ok()
        .and_then(|s| s.parse().ok())
        .filter(|&k| k > 0);
    if curve_every.is_some() {
        println!(
            "curve: step,tokens,distilled_ppl,recovery_vs_ptq,gap_to_fp (fp {ppl_fp:.3}, ptq {ppl_ptq:.3e})"
        );
    }

    // Optional LR schedule (linear warmup → cosine decay). At the gate's constant LR the run descends
    // fast then oscillates on a plateau without settling (WikiText-2: 3250 → 431 by step 2800, then
    // flat at 460–570 for 2200 more steps) — decaying the LR is the standard remedy. Opt-in via
    // TRITIUM_DISTILL_WARMUP=<steps>, so the committed gate's constant-LR behaviour is unchanged.
    let lr_sched = std::env::var("TRITIUM_DISTILL_WARMUP")
        .ok()
        .and_then(|s| s.parse::<u64>().ok())
        .map(|warmup| LrSchedule::new(LR, LR * 0.05, warmup.min(steps), steps.max(1)));
    if lr_sched.is_some() {
        println!(
            "lr schedule: warmup+cosine, peak {LR:e} → min {:e}",
            LR * 0.05
        );
    }

    // TRITIUM_DISTILL_SEED rotates the training-window order (data-order seed) — the
    // stochasticity axis for paper error bars. Default 0 reproduces the committed runs.
    let data_seed: usize = std::env::var("TRITIUM_DISTILL_SEED")
        .ok()
        .and_then(|s| s.parse().ok())
        .unwrap_or(0);
    if data_seed != 0 {
        eprintln!("data-order seed: {data_seed} (window rotation)");
    }
    // Sherry (annealed fp residual): TRITIUM_DISTILL_SHERRY=<alpha0> blends `alpha*master` into each
    // reconstruction, cosine-annealed to 0 over the FIRST HALF of training so the model trains as pure
    // ternary for the whole back half (and the final eval, which always quantizes hard, is honest).
    // Off by default.
    let sherry_start: Option<f32> = std::env::var("TRITIUM_DISTILL_SHERRY")
        .ok()
        .and_then(|s| s.parse().ok())
        .filter(|a: &f32| *a > 0.0 && *a <= 1.0);
    let sherry_total = steps.div_ceil(2).max(1);
    if let Some(a0) = sherry_start {
        println!("sherry: fp-residual alpha {a0} → 0 (cosine) over the first {sherry_total} steps");
    }

    let mut step_ms = 0.0f64;
    for step in 1..=steps {
        let t0 = Instant::now();
        if let Some(sched) = lr_sched.as_ref() {
            trainer.set_lr(sched.lr(step - 1)); // `step` is 1-based; the schedule is 0-based
        }
        if let Some(a0) = sherry_start {
            trainer.set_sherry_alpha(ste::sherry_alpha(a0, step - 1, sherry_total));
        }
        let wi = ((step - 1) as usize + data_seed) % windows.len();
        let toks = windows[wi];
        let tokens_i32: Vec<i32> = toks.iter().map(|&t| t as i32).collect();

        let target = if let Some(cache) = teacher_cache.as_mut() {
            cache.read_window(wi as u64, &mut cached_target).unwrap();
            DeviceTensor::upload(&backend, &cached_target).unwrap()
        } else {
            // Keep the online teacher as the Track-0-compatible fallback.
            let tprobs = {
                let mut tape = DeviceTape::new(&backend, a.vocab).unwrap();
                let (logits, _) = device_forward(&mut tape, &a, &fp, &tokens_i32, seq_len);
                row_softmax(&tape.value(logits).unwrap(), a.vocab)
            };
            DeviceTensor::upload(&backend, &tprobs).unwrap()
        };

        trainer.prepare_quantized().unwrap();
        let resident: Vec<_> = (0..fp.len())
            .map(|i| trainer.quantized(i).unwrap())
            .collect();
        let grads = {
            let mut tape = DeviceTape::new(&backend, a.vocab).unwrap();
            if let Some(tc) = tc.as_ref() {
                tape = tape.with_tensor_core(tc);
            }
            let (logits, wids) =
                device_forward_resident(&mut tape, &a, &resident, &tokens_i32, seq_len);
            tape.xent_backward_device(logits, &target, seq_len, a.vocab, &wids)
                .unwrap()
        };
        drop(resident);
        trainer.step(grads, step).unwrap();

        step_ms += t0.elapsed().as_secs_f64() * 1e3;
        if step % 10 == 0 || step == 1 {
            eprintln!("  resident step {step}/{steps} (win {wi})");
        }

        // Checkpoint eval: download the resident masters (read-only copy — training state is
        // untouched), quantize, and score the disjoint held-out set. One point on the curve.
        if let Some(k) = curve_every
            && (step % k == 0 || step == steps)
        {
            let ckpt: Vec<Vec<f32>> = (0..fp.len())
                .map(|i| trainer.download_master(i).unwrap())
                .zip(&shapes)
                .enumerate()
                .map(|(i, (wf, &(n, kk)))| deploy_quantize(&wf, n, kk, i))
                .collect();
            let ppl = perplexity_windowed(&ckpt, &a, &eval_ids, EVAL_WINDOW);
            let tokens = step as usize * seq_len;
            println!(
                "curve: {step},{tokens},{ppl:.3},{:.1},{:.3}",
                ppl_ptq / ppl,
                ppl / ppl_fp
            );
        }
    }

    let lat: Vec<Vec<f32>> = (0..fp.len())
        .map(|i| trainer.download_master(i).unwrap())
        .collect();
    let distilled: Vec<Vec<f32>> = lat
        .iter()
        .zip(&shapes)
        .enumerate()
        .map(|(i, (wf, &(n, k)))| deploy_quantize(wf, n, k, i))
        .collect();
    let ppl_distilled = perplexity_windowed(&distilled, &a, &eval_ids, EVAL_WINDOW);
    let recovery = ppl_ptq / ppl_distilled;
    let mean_ms = step_ms / steps as f64;
    let host_probability_copies = if teacher_cache.is_some() { 1 } else { 2 };
    let host_mib = (host_probability_copies * seq_len * a.vocab * std::mem::size_of::<f32>())
        as f64
        / (1024.0 * 1024.0);
    let teacher_source = if teacher_cache.is_some() {
        "offline cache"
    } else {
        "online device teacher"
    };
    println!(
        "0027 A RESIDENT SALT distillation (planes={planes}, {steps} steps): fp ppl {ppl_fp:.3} | \
         PTQ ppl {ppl_ptq:.3e} | distilled ppl {ppl_distilled:.3} | recovers {recovery:.0}x. \
         Mean step {mean_ms:.0}ms vs Track-0 {TRACK0_STEP_MS:.0}ms; student parameter path 100% \
         device-resident, {teacher_source}, remaining teacher probability traffic {host_mib:.1} \
         MiB/step."
    );

    assert!(ppl_ptq > ppl_fp, "PTQ must degrade held-out ppl");
    assert!(
        recovery >= 950.0,
        "resident trainer recovered only {recovery:.0}x vs PTQ (expected about 960x)"
    );
    assert!(
        mean_ms < TRACK0_STEP_MS,
        "resident mean step {mean_ms:.0}ms did not beat Track-0 {TRACK0_STEP_MS:.0}ms"
    );
}

#[cfg(feature = "cuda")]
#[test]
#[ignore = "CUDA teacher-cache I/O benchmark; run explicitly with --ignored --nocapture"]
fn teacher_cache_fetch_and_upload_is_bounded() {
    use std::time::Instant;

    use tritium_cuda::CudaBackend;
    use tritium_cuda::train::DeviceTensor;
    use tritium_format::TeacherCacheHeader;
    use tritium_nn::{TeacherCacheReader, TeacherCacheWriter};

    let backend = match CudaBackend::new(0) {
        Ok(backend) => backend,
        Err(error) => {
            eprintln!("skipping teacher_cache_fetch_and_upload_is_bounded: no CUDA ({error})");
            return;
        }
    };
    let header = TeacherCacheHeader {
        seq_len: TRAIN_SEQ as u32,
        vocab: 49_152,
        windows: 1,
        model_hash: [0x11; 32],
        corpus_hash: [0x22; 32],
    };
    let path = std::env::temp_dir().join(format!(
        "tritium-teacher-cache-bench-{}.ttpr",
        std::process::id()
    ));
    let probabilities = vec![1.0 / header.vocab as f32; header.window_elements().unwrap()];
    let mut writer = TeacherCacheWriter::create(&path, header).unwrap();
    writer.write_window(&probabilities).unwrap();
    writer.finish().unwrap();
    let mut reader = TeacherCacheReader::open(&path, &header).unwrap();
    let mut host = vec![0.0; probabilities.len()];
    let mut sample = || {
        let start = Instant::now();
        reader.read_window(0, &mut host).unwrap();
        let tensor = DeviceTensor::upload(&backend, &host).unwrap();
        drop(tensor);
        start.elapsed().as_secs_f64() * 1e3
    };
    for _ in 0..5 {
        sample();
    }
    let mut samples: Vec<_> = (0..21).map(|_| sample()).collect();
    samples.sort_by(f64::total_cmp);
    let median_ms = samples[10];
    eprintln!(
        "0027 Phase-0 dense teacher cache: {:.1} MiB fetch+CUDA upload median {median_ms:.2}ms",
        probabilities.len() as f64 * 4.0 / (1024.0 * 1024.0)
    );
    assert!(
        median_ms < 50.0,
        "teacher cache fetch+upload {median_ms:.2}ms exceeds 50ms hot-step budget"
    );
    std::fs::remove_file(path).unwrap();
}
