//! HELD-OUT SALT distillation (plan 0042) — the generalization test, and the prerequisite for any
//! publishable number. Unlike `salt_distill_real` (which trains + evaluates on ONE sequence =
//! in-sample memorization), this distills SmolLM2 on a TRAIN token split and measures perplexity on
//! a disjoint HELD-OUT split it never trains on. Recovering held-out ppl vs PTQ = real generalization.
//!
//! Corpus: `tools/reference/heldout_corpus.json` ({train_ids, eval_ids}), generated by
//! `tools/gen_corpus.py` (a public-domain text tokenized with the model's own tokenizer).
//! `#[ignore]`d (slow, needs SmolLM2-135M); run:
//!
//! ```text
//! cargo test -p tritium-nn --release --test salt_distill_heldout -- --ignored --nocapture
//! ```

mod common;

use std::path::PathBuf;

use common::{extract, forward, logits_of, perplexity};
use tritium_nn::ModelRunner;
use tritium_train::ops::ste;
use tritium_train::{AdamW, Optimizer, Tape};

const T: usize = 2;
const TRAIN_SEQ: usize = 32; // window length for the training corpus
const STEPS: u64 = 40; // committed-gate default; TRITIUM_DISTILL_STEPS overrides for a real run
const LR: f32 = 2e-3;

fn model_dir() -> PathBuf {
    let home = std::env::var("HOME").unwrap_or_default();
    PathBuf::from(home).join(".cache/tritium-models/smollm2-135m")
}

fn corpus() -> (Vec<u32>, Vec<u32>) {
    // TRITIUM_CORPUS overrides the committed fixture (for the large-budget endpoint sweeps, which
    // use a bigger locally-generated corpus we don't commit as a multi-MB fixture).
    let path = std::env::var("TRITIUM_CORPUS").unwrap_or_else(|_| {
        concat!(
            env!("CARGO_MANIFEST_DIR"),
            "/../../tools/reference/heldout_corpus.json"
        )
        .to_string()
    });
    let j: serde_json::Value =
        serde_json::from_slice(&std::fs::read(&path).expect("corpus json")).expect("parse");
    let ids = |k: &str| {
        j[k].as_array()
            .expect(k)
            .iter()
            .map(|v| v.as_u64().expect("id") as u32)
            .collect::<Vec<u32>>()
    };
    (ids("train_ids"), ids("eval_ids"))
}

fn row_softmax(logits: &[f32], vocab: usize) -> Vec<f32> {
    let mut p = logits.to_vec();
    for row in p.chunks_mut(vocab) {
        let m = row.iter().copied().fold(f32::NEG_INFINITY, f32::max);
        let mut s = 0.0f32;
        for v in row.iter_mut() {
            *v = (*v - m).exp();
            s += *v;
        }
        for v in row.iter_mut() {
            *v /= s;
        }
    }
    p
}

#[test]
#[ignore = "slow held-out real-model distillation; needs SmolLM2-135M; run explicitly"]
fn salt_distillation_recovers_heldout_perplexity() {
    let dir = model_dir();
    if !dir.join("model.safetensors").exists() {
        eprintln!("skipping: {} absent", dir.display());
        return;
    }
    let steps: u64 = std::env::var("TRITIUM_DISTILL_STEPS")
        .ok()
        .and_then(|s| s.parse().ok())
        .unwrap_or(STEPS);

    let runner =
        ModelRunner::from_hf(&dir, Box::new(tritium_cpu::CpuBackend::new())).expect("from_hf");
    let (a, fp, shapes) = extract(&runner);
    let (mut train_ids, eval_ids) = corpus();
    // Cap the train pool to sweep the recovery-vs-tokens curve (held-out set is fixed & disjoint).
    if let Some(n) = std::env::var("TRITIUM_TRAIN_TOKENS")
        .ok()
        .and_then(|s| s.parse().ok())
    {
        train_ids.truncate(n);
    }

    // Non-overlapping training windows.
    let windows: Vec<&[u32]> = train_ids.chunks_exact(TRAIN_SEQ).collect();
    assert!(!windows.is_empty(), "train corpus shorter than one window");

    // Held-out baselines (fp + full PTQ), on the disjoint eval split.
    let ppl_fp = perplexity(&logits_of(&fp, &a, &eval_ids), &eval_ids, a.vocab);
    let ptq: Vec<Vec<f32>> = fp
        .iter()
        .zip(&shapes)
        .map(|(wf, &(n, k))| ste::salt_quantize_forward(wf, n, k, T))
        .collect();
    let ppl_ptq = perplexity(&logits_of(&ptq, &a, &eval_ids), &eval_ids, a.vocab);

    // Distill on the TRAIN windows (cycled), AdamW; eval held-out afterwards.
    let mut lat = fp.clone();
    let opt = AdamW::new(LR);
    let mut states: Vec<_> = lat.iter().map(|w| opt.init_state(w.len())).collect();
    let (mut first, mut last) = (f32::NAN, f32::NAN);

    // Optional GPU student (plan 0043 Phase 1): route the tape's `dense_matmul`s to the 4090 via the
    // bit-exact `train_grad.cu` kernels. Opt-in with `TRITIUM_DISTILL_GPU=1 --features cuda`; the
    // teacher forward + `salt_ste` + norm/softmax glue stay on the CPU host (device-resident = P2).
    #[cfg(feature = "cuda")]
    let gpu: Option<std::rc::Rc<dyn tritium_train::TrainGemm>> =
        std::env::var("TRITIUM_DISTILL_GPU").is_ok().then(|| {
            std::rc::Rc::new(tritium_cuda::train::GpuGemm::new(0).expect("open CUDA device"))
                as std::rc::Rc<dyn tritium_train::TrainGemm>
        });
    #[cfg(feature = "cuda")]
    let backend = if gpu.is_some() { "GPU" } else { "CPU" };
    #[cfg(not(feature = "cuda"))]
    let backend = "CPU";
    let mut step_ms = 0.0f64;

    for step in 1..=steps {
        let t_start = std::time::Instant::now();
        let wi = ((step - 1) as usize) % windows.len();
        let toks = windows[wi];
        // Teacher soft targets for this window, computed on the fly (O(1) memory — precomputing all
        // windows' full-vocab probs is ~26GB at the 128k-token endpoint).
        let tprobs = row_softmax(&logits_of(&fp, &a, toks), a.vocab);
        #[cfg(feature = "cuda")]
        let mut t = match &gpu {
            Some(e) => Tape::with_gemm(e.clone()),
            None => Tape::new(),
        };
        #[cfg(not(feature = "cuda"))]
        let mut t = Tape::new();
        let mut leaf_ids = Vec::with_capacity(lat.len());
        let mut ste_ids = Vec::with_capacity(lat.len());
        for (i, wv) in lat.iter().enumerate() {
            let l = t.leaf(wv.clone());
            let (n, k) = shapes[i];
            ste_ids.push(t.salt_ste(l, n, k, T));
            leaf_ids.push(l);
        }
        let logits = forward(&mut t, &ste_ids, &a, toks);
        let tg = t.leaf(tprobs);
        let l = t.softmax_xent(logits, tg, TRAIN_SEQ, a.vocab);
        let lv = t.value(l)[0];
        if step == 1 {
            first = lv;
        }
        last = lv;
        let grads = t.backward(l);
        for i in 0..lat.len() {
            opt.step(step, &mut lat[i], &grads[leaf_ids[i]], &mut states[i]);
        }
        step_ms += t_start.elapsed().as_secs_f64() * 1e3;
        if step % 10 == 0 || step == 1 {
            eprintln!("  step {step}/{steps} (win {wi})  train-xent {lv:.4}");
        }
    }
    eprintln!(
        "  [{backend}] mean step {:.0}ms over {steps} steps (teacher+salt_ste CPU; matmuls {backend})",
        step_ms / steps as f64
    );
    let distilled: Vec<Vec<f32>> = lat
        .iter()
        .zip(&shapes)
        .map(|(wf, &(n, k))| ste::salt_quantize_forward(wf, n, k, T))
        .collect();
    let ppl_distilled = perplexity(&logits_of(&distilled, &a, &eval_ids), &eval_ids, a.vocab);

    println!(
        "0042 HELD-OUT SmolLM2 distillation (T={T}, {steps} steps, train {} tok / {} windows, eval {} HELD-OUT tok): \
         fp ppl {ppl_fp:.3} | PTQ ppl {ppl_ptq:.3e} | distilled ppl {ppl_distilled:.3}  \
         (train-xent {first:.3}→{last:.3}). GENERALIZES: held-out ppl {:.0}× better than PTQ on unseen text \
         (not memorization). DATA-LIMITED: still {:.1}× fp at this budget — the residual gap is what more \
         tokens close (a point on the recovery-vs-tokens curve; sweep TRITIUM_TRAIN_TOKENS to trace it, 0042).",
        train_ids.len(),
        windows.len(),
        eval_ids.len(),
        ppl_ptq / ppl_distilled,
        ppl_distilled / ppl_fp,
    );

    assert!(ppl_ptq > ppl_fp, "PTQ must degrade held-out ppl");
    assert!(last < first, "training surrogate must decrease");
    // The load-bearing claim: end-to-end distillation on TRAIN recovers HELD-OUT ppl vs PTQ — real
    // generalization, not the in-sample memorization of salt_distill_real. (Full recovery to fp
    // needs more tokens — the recovery-vs-tokens curve; this budget is one point on it.)
    assert!(
        ppl_distilled < 0.5 * ppl_ptq,
        "distillation must recover held-out ppl vs PTQ: {ppl_distilled:.3} vs PTQ {ppl_ptq:.3e}"
    );
}
