//! GGUF-embedded BPE tokenizer conformance (model-gated, `tokenizer` feature).
//!
//! The committed reference (`tools/reference/bitnet_accept.json`, generated by
//! `transformers`) pins the prompt text AND its token ids — a free conformance
//! vector: `GgufBpeTokenizer` must encode the same text to the same ids
//! (BOS-prepended, exactly as `gen_reference.py` tokenized it).

#![cfg(feature = "tokenizer")]

use std::path::Path;

use tritium_nn::{GgufBpeTokenizer, Tokenizer};

const GGUF_PATH: &str =
    "/home/brianklam/.cache/tritium-models/bitnet-2b4t-gguf/ggml-model-i2_s.gguf";
const REF_PATH: &str = concat!(
    env!("CARGO_MANIFEST_DIR"),
    "/../../tools/reference/bitnet_accept.json"
);

#[test]
fn bpe_matches_transformers_reference() {
    if !Path::new(GGUF_PATH).exists() {
        eprintln!("skipping: {GGUF_PATH} absent (gated real-model test)");
        return;
    }
    let bytes = std::fs::read(GGUF_PATH).expect("read gguf");
    let file = tritium_format::read_gguf(&bytes).expect("parse gguf");
    let tok = GgufBpeTokenizer::from_gguf(&file).expect("build tokenizer from gguf");

    let reference: serde_json::Value =
        serde_json::from_slice(&std::fs::read(REF_PATH).expect("read reference"))
            .expect("parse reference");
    let prompt = reference["prompt"].as_str().expect("prompt");
    let want: Vec<u32> = reference["token_ids"]
        .as_array()
        .expect("token_ids")
        .iter()
        .map(|v| v.as_u64().expect("id") as u32)
        .collect();

    // Encode conformance: same text -> same ids as transformers (incl. BOS).
    let got = tok.encode(prompt).expect("encode");
    assert_eq!(
        got, want,
        "encode({prompt:?}) must reproduce the transformers reference ids"
    );

    // Decode inverts (BOS is special -> dropped; text round-trips).
    let text = tok.decode(&got).expect("decode");
    assert_eq!(text, prompt, "decode(encode(p)) must round-trip");

    // Special ids: BOS from metadata; EOS prefers <|eot_id|> (the chat turn
    // terminator) over the converter's <|end_of_text|>.
    assert_eq!(tok.bos(), 128_000);
    assert_eq!(tok.eos(), 128_009, "eos must be <|eot_id|>");

    // Special tokens are recognised verbatim in text (the chat template
    // embeds <|eot_id|> between turns) and dropped from decoded output.
    let ids = tok.encode("Hi<|eot_id|>there").expect("encode specials");
    assert!(
        ids.contains(&128_009),
        "<|eot_id|> must map to its control id, got {ids:?}"
    );
    let round = tok.decode(&ids).expect("decode specials");
    assert_eq!(round, "Hithere", "specials are dropped from decode output");

    // Whitespace/multibyte sanity: byte-level BPE must round-trip UTF-8.
    for s in ["  leading spaces", "naïve café — em-dash", "日本語テスト"] {
        let ids = tok.encode(s).expect("encode");
        assert_eq!(tok.decode(&ids).expect("decode"), s, "round-trip {s:?}");
    }
}
