{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "tritium.fullname" . }}
  labels:
    {{- include "tritium.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "tritium.selectorLabels" . | nindent 6 }}
  policyTypes: [Ingress, Egress]
  ingress:
    - from:
        - namespaceSelector:
            {{- if .Values.networkPolicy.ingressNamespaceSelector }}
            {{- toYaml .Values.networkPolicy.ingressNamespaceSelector | nindent 12 }}
            {{- else }}
            matchLabels:
              kubernetes.io/metadata.name: {{ .Release.Namespace | quote }}
            {{- end }}
      ports:
        - protocol: TCP
          port: {{ .Values.service.port }}
    {{- if .Values.serviceMonitor.enabled }}
    - from:
        - namespaceSelector:
            {{- toYaml .Values.serviceMonitor.ingressNamespaceSelector | nindent 12 }}
      ports:
        - protocol: TCP
          port: {{ .Values.service.port }}
    {{- end }}
  egress:
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
          podSelector:
            matchLabels:
              k8s-app: kube-dns
      ports:
        - {protocol: UDP, port: 53}
        - {protocol: TCP, port: 53}
{{- end }}
