#!/usr/bin/env bash
# Publish-readiness gate (ADR 0011 / v0.90): every workspace crate packages cleanly
# into a valid `.crate` — manifest valid, all referenced files present, internal
# deps version-pinned and ordered.
#
# Why `cargo package --workspace` and not per-crate `cargo publish --dry-run`:
# this workspace has not been published to crates.io, so a per-crate
# `cargo publish --dry-run` / `cargo package -p <x>` fails to "prepare for upload"
# because each crate's internal deps (e.g. `tritium-core = "0.6.x"`) aren't on
# crates.io yet (a chicken-and-egg only resolvable by an ordered release-time
# publish). Cargo rewrites path deps to registry deps while preparing an upload,
# so a prerelease absent from crates.io still fails resolution even for a
# workspace package. We inject an ephemeral `[patch.crates-io]` table pointing at
# every workspace member; Cargo then resolves those rewritten requirements against
# the exact local source while retaining registry-style manifests in each archive.
# The verify-build is already covered by the cpu-only-green lane. `--frozen` makes
# archive assembly fail on lockfile drift or a network dependency; clean offline
# installation of the resulting archives remains the stricter local-RC gate.
set -euo pipefail

cd "$(dirname "${BASH_SOURCE[0]}")/.."

./scripts/check-release-version.py
python3 ./scripts/sync-packaged-training-spec.py --check
unpublished=$(
  cargo metadata --locked --no-deps --format-version 1 |
    # cargo metadata encodes `publish = false` as []; null means publishable.
    python3 -c 'import json,sys; print("\n".join(p["name"] for p in json.load(sys.stdin)["packages"] if p.get("publish") == []))'
)
exclude_args=()
while IFS= read -r package; do
  [[ -z "$package" ]] && continue
  exclude_args+=(--exclude "$package")
done <<< "$unpublished"

# `cargo package` resolves rewritten path dependencies from the registry. During
# a local prerelease those exact versions are intentionally not published yet.
# Keep patch file outside checkout so candidate admission cannot mistake it for
# release input, and use absolute paths because Cargo resolves config-file paths
# relative to config location.
patch_config="$(mktemp "${TMPDIR:-/tmp}/tritium-publish-patch.XXXXXX.toml")"
trap 'rm -f "$patch_config"' EXIT
python3 - "$patch_config" <<'PY'
import json
import pathlib
import subprocess
import sys

output = pathlib.Path(sys.argv[1])
metadata = json.loads(subprocess.check_output(
    ["cargo", "metadata", "--locked", "--no-deps", "--format-version", "1"],
    text=True,
))
lines = [
    "# Ephemeral local prerelease patches; generated by scripts/check-publish.sh.",
    "[patch.crates-io]",
]
for package in sorted(
    (item for item in metadata["packages"] if item.get("publish") != []),
    key=lambda item: item["name"],
):
    name = package["name"]
    member_dir = pathlib.Path(package["manifest_path"]).parent.resolve()
    lines.extend([
        f'"{name}" = {{ path = "{member_dir.as_posix()}" }}',
    ])
output.write_text("\n".join(lines) + "\n", encoding="utf-8")
PY

echo "publish-readiness: cargo package --workspace --frozen --no-verify (publishable crates only; local prerelease patches)"
cargo package --workspace "${exclude_args[@]}" --frozen --no-verify --quiet --config "$patch_config"
echo "OK: every publishable workspace crate packages cleanly (manifests + files)."
