/* tritium.h — C ABI for Tritium inference. GENERATED by cbindgen from
   tritium-ffi; do not edit by hand. Regenerate: cargo test -p tritium-ffi (the
   header_is_current drift test prints the command on mismatch). */

#ifndef TRITIUM_FFI_H
#define TRITIUM_FFI_H

#pragma once

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

// C ABI version. Bump on any breaking change to the exported symbols/layout.
#define TRITIUM_ABI_VERSION 1

// Result code returned by the C API. `Ok` is 0; all errors are non-zero.
typedef enum TritiumStatus {
    // Success.
    TritiumStatus_Ok = 0,
    // A required pointer argument was null.
    TritiumStatus_NullArg = 1,
    // Loading/parsing the model failed.
    TritiumStatus_Load = 2,
    // Generation failed in the backend.
    TritiumStatus_Generate = 3,
    // The output buffer was too small; `*out_len` holds the required length.
    TritiumStatus_BufferTooSmall = 4,
    // An internal panic was caught at the boundary (should not happen).
    TritiumStatus_Panic = 5,
} TritiumStatus;

// Opaque handle to a loaded model (a `ModelRunner`). Created by
// [`tritium_model_load_file`], released by [`tritium_model_free`].
typedef struct TritiumModel TritiumModel;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

// Returns the C ABI version ([`TRITIUM_ABI_VERSION`]).
uint32_t tritium_abi_version(void);

// Returns the crate version as a static, NUL-terminated C string (never null).
const char *tritium_version(void);

// Load a GGUF model from `path` (a NUL-terminated UTF-8 string) on the CPU
// backend. Returns an owned handle, or null on failure; if `out_status` is
// non-null it receives the [`TritiumStatus`]. Free the handle with
// [`tritium_model_free`].
//
// # Safety
// `path` must be a valid NUL-terminated C string (or null); `out_status` must be
// null or a valid writable `TritiumStatus*`.
struct TritiumModel *tritium_model_load_file(const char *path, enum TritiumStatus *out_status);

// Greedily generate up to `max_new` tokens from `prompt` (`prompt_len` token
// IDs), stopping early at `eos`. Writes up to `out_cap` token IDs into `out` and
// sets `*out_len` to the number generated. If the generated count exceeds
// `out_cap`, returns [`TritiumStatus::BufferTooSmall`] with `*out_len` set to the
// required length (nothing is written).
//
// # Safety
// `model` must be a live handle from [`tritium_model_load_file`]; `prompt` must
// point to `prompt_len` `u32`s (or be null iff `prompt_len == 0`); `out` must
// point to `out_cap` writable `u32`s (or be null iff `out_cap == 0`); `out_len`
// must be a valid writable `usize*`. Do not call concurrently on one `model`.
enum TritiumStatus tritium_generate(struct TritiumModel *model,
                                    const uint32_t *prompt,
                                    uintptr_t prompt_len,
                                    uint32_t max_new,
                                    uint32_t eos,
                                    uint32_t *out,
                                    uintptr_t out_cap,
                                    uintptr_t *out_len);

// Free a model handle returned by [`tritium_model_load_file`]. Null-safe;
// double-free is the caller's responsibility (do not call twice on one handle).
//
// # Safety
// `model` must be null or a handle from [`tritium_model_load_file`] not yet freed.
void tritium_model_free(struct TritiumModel *model);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* TRITIUM_FFI_H */
